name: Arduino CI Workflow

on:
  push:
    branches:
      - gitlabCI-to-githubCI
  pull_request:
    branches:
      - gitlabCI-to-githubCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
          sudo apt-get install -y python3 python3-pip
          pip3 install pyserial
          sudo apt-get install -y git

      - name: Configure Arduino CLI
        run: |
          export ARDUINO_CORE_URL="https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json"
          arduino-cli config init --additional-urls "${ARDUINO_CORE_URL}"
          arduino-cli core update-index
          arduino-cli core install Seeeduino:samd

      - name: Clone required libraries
        run: |
          git clone https://github.com/0015/TP_Arduino_DigitalRain_Anim.git
          git clone https://github.com/Indomet/RawImage
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_LIS3DHTR.git
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_LineChart
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_SFUD
          git clone https://github.com/Seeed-Studio/Seeed_Arduino_FS

      - name: Build sketch
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "pubsubclient"
          arduino-cli compile -b Seeeduino:samd:seeed_wio_terminal seeed-wio-terminal/WioPlay/WioPlay.ino --library TP_Arduino_DigitalRain_Anim --library RawImage/RawImage --library Seeed_Arduino_LIS3DHTR --library Seeed_Arduino_LineChart --library Seeed_Arduino_mbedtls --library Seeed_Arduino_rpcUnified --library Seeed_Arduino_rpcUnified --library Seeed_Arduino_rpcWiFi --library Seeed_Arduino_SFUD --library Seeed_Arduino_FS
