name: Java CI with Maven

on:
  push:
    branches:
      - gitlabCI-to-githubCI
  pull_request:
    branches:
      - gitlabCI-to-githubCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Print current directory
        run: pwd
                 
      - name: Change to NoteParser directory
        run: cd NoteParser

      - name: Print current directory 2
        run: pwd
                 
      - name: Build with Maven
        run: mvn --batch-mode --show-version --errors --no-transfer-progress install

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Print current directory 3
        run: pwd
                 
      - name: Change to NoteParser directory
        run: cd NoteParser

      - name: Print current directory 4
        run: pwd
                 
      - name: Test with Maven
        run: mvn --batch-mode --show-version --errors --no-transfer-progress test
